name: driver

x-common-env: &common_env
  DISPLAY: ${DISPLAY}
  NVIDIA_VISIBLE_DEVICES: all
  NVIDIA_DRIVER_CAPABILITIES: all
  OMP_WAIT_POLICY: passive
  TERM: xterm-256color
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  ROS_LOCALHOST_ONLY: 1

x-common: &common
  tty: true
  network_mode: host
  pid: "host"
  ipc: "host"
  privileged: true
  user: "Elaina"
  stdin_open: true

services:
  zenoh_service:
    image: elainasuki/rc2026:driverLogic
    container_name: zenoh_runtime
    <<: *common
    entrypoint:
      - /bin/bash
      - -i
      - -c
      - |
        if pgrep -x 'rmw_zenohd' >/dev/null; then
          echo '[zenoh] rmw_zenohd already running'
          exec sleep infinity
        else
          echo '[zenoh] starting rmw_zenohd...'
          exec ros2 run rmw_zenoh_cpp rmw_zenohd
        fi
  driverLogic_service:
    image: elainasuki/rc2026:driverLogic
    container_name: driverLogic_runtime
    <<: *common
    environment:
      <<: *common_env
      PYTHONPATH: /home/Elaina/ros2_ws/src:$$PYTHONPATH
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - driverLogic_volume:/home/Elaina/ros2_ws
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
    working_dir: "/home/Elaina/ros2_ws"
    entrypoint: ["/bin/bash", "-i", "-c", "source ~/.bashrc && ros2 launch my_driver hik_camera.launch.py"]
  opencv_service:
    image: elainasuki/rc2026:yolo-ros
    container_name: opencv_runtime
    <<: *common
    environment:
      <<: *common_env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - opencv_volume:/home/Elaina/yolo
      - /dev:/dev
    working_dir: "/home/Elaina/yolo"
    entrypoint: ["/bin/bash", "-i", "-c", "python3 ~/yolo/spear/ros2_arucopnp_serial_node.py"]

volumes:
  driverLogic_volume:
    external: true
    name: driverLogic_volume
  opencv_volume:
    external: true
    name: ros2_opencv_volume

