register_keys:
  # 强制要求 USB 3.0；重定位地图传输建议开启
  strict_usb3.0_check: 1

  # 2：将 Odin 时间对齐到主机时间轴
  use_host_ros_time: 2

  # 数据流控制
  streamctrl: 1

  # 原始 JPEG 图像
  sendrgbcompressed: 1

  # 主机解码后的 BGR8 图像
  sendrgb: 1

  # 去畸变 RGB 图像，依赖 sendrgb
  sendrgbundistort: 1

  # IMU 数据
  sendimu: 1

  # 开启 SDK IMU 平滑发送
  enable_imu_smooth: 1

  # IMU 平滑发送频率
  imu_smooth_frequency: 400

  # Odin 里程计数据
  sendodom: 1

  # 发布 odom -> odin1_base_link TF
  send_odom_baselink_tf: 1

  # 原始 DTOF 点云
  senddtof: 1

  # 原始点云置信度阈值
  cloud_raw_confidence_threshold: 35

  # DTOF 最大支持帧率：145 表示 14.5 fps
  dtof_fps: 145

  # SLAM 点云
  sendcloudslam: 1

  # 主机渲染点云
  sendcloudrender: 1

  # 深度补全，计算资源消耗较高
  senddepth: 1

  # 点云重投影
  sendreprojection: 1

  # 图像叠加
  sendoverlay: 1

  overlay_reprojected_topic: "/odin1/reprojected_image"
  overlay_camera_topic: "/odin1/image/undistorted"
  overlay_output_topic: "/odin1/overlay_image"
  overlay_alpha: 0.6

  # 记录 RGB、里程计和 SLAM 点云
  recorddata: 1

  # 保存设备运行状态
  devstatuslog: 1

  # 保存驱动日志
  save_log: 1

  # 发布 DTOF 原始灰度强度图
  pubintensitygray: 1

  # 显示运动路径
  showpath: 1

  # 显示相机位姿
  showcamerapose: 1

  # 2：重定位模式
  custom_map_mode: 2

  # 初始位姿：[x, y, z, qx, qy, qz, qw]
  custom_init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

  # 重定位地图绝对路径
  relocalization_map_abs_path: "/home/Elaina/ros2_ws/src/odin_ros_driver/recorddata/20260702_094903/export_map/map_merged.bin"

  # 地图保存配置；重定位模式下一般不会使用
  mapping_result_dest_dir: ""
  mapping_result_file_name: ""